# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

target 'AppDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppDemo

  pod 'smartframework', :path => '../SmartFramework'
  pod 'smartlogger', :path => '../../SmartLogger/SmartLogger'
  pod 'smartsocial', :path => '../../SmartSocial/SmartSocial'

end
